service: graphql-api # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs8.10

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: get