service: graphql-api # NOTE: update this with your service name
provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
functions:
  query:
    handler: handler.query
    environment:
      SLS_DEBUG: true
    events:
      - http:
          path: graphql
          method: post
          cors: false
          integration: lambda-proxy
      - http:
          path: graphql
          method: get 
          cors: false
          integration: lambda-proxy